import AuthProvider from './components/authProvider';
import Sidebar from './components/navbar';
import SessionManager from './components/sessionManager';
import './globals.css';

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <AuthProvider>
                    <SessionManager />
                    <div className="flex min-h-screen">
                        <Sidebar />
                        <main className="flex-1 bg-[#0e0e12] border-l-2 border-white p-6 overflow-y-auto">
                            {children}
                        </main>
                    </div>
                </AuthProvider>
            </body>
        </html>
    );
}
